[package]
name = "rt_ffi"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
libc = "0.2" # Often needed for FFI types if not using core::ffi exclusively

[build-dependencies]
bindgen = "0.71.0"